# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiOvQ0XFhbONGqDrjPAUxtMSxjDKPx3E
"""

import pandas as pd
import numpy as np

data = pd.read_csv("/content/student_performance_dirty (1).csv")

print(data)

print(data.head())

print(data.tail())

print(data.columns)

print(data.info())

print(data.describe())

print(data.isnull())

print(data.isnull().sum())

data.fillna(data.mean(numeric_only=True), inplace=True)

print(data)

data.fillna(data.mode().iloc[0], inplace=True)

print(data)

print(data.isnull().sum())

print(data.duplicated())

print(data[data.duplicated()])

data.drop_duplicates(inplace=True)

print(data)

data.reset_index(drop=True, inplace=True)

print(data)

print(data.dtypes)

categorical_columns = data.select_dtypes(include='object').columns

for col in categorical_columns:

    data[col] = data[col].str.lower()

    data[col] = data[col].str.strip()

print(data)

numeric_columns = data.select_dtypes(include=np.number).columns

for col in numeric_columns:

    Q1 = data[col].quantile(0.25)

    Q3 = data[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_threshold = Q1 - 1.5 * IQR

    upper_threshold = Q3 + 1.5 * IQR

    outliers = data[
        (data[col] < lower_threshold) |
        (data[col] > upper_threshold)
    ]

    print("Outliers in", col)

    print(outliers)

for col in numeric_columns:

    Q1 = data[col].quantile(0.25)

    Q3 = data[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_threshold = Q1 - 1.5 * IQR

    upper_threshold = Q3 + 1.5 * IQR

    data = data[
        (data[col] >= lower_threshold) &
        (data[col] <= upper_threshold)
    ]

print(data)

data.reset_index(drop=True, inplace=True)

print(data)

data.to_csv("cleaned_dataset.csv", index=False)

print("Dataset Cleaned Successfully")

import matplotlib.pyplot as plt
import seaborn as sns

data= pd.read_csv("student_performance_dirty.csv")

print(data.describe())

sns.heatmap(
    data.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.title("Heatmap: Correlation Between Numric Variables")
plt.show()

plt.hist(
    data["Exam_Score"],
    bins=10,
    color='blue',
    edgecolor='black'
)
plt.title("Histogram of Exam Score Distribution")
plt.xlabel("Exam Score")
plt.ylabel("frequency")
plt.show()
sns.scatterplot(
 data=data,
 x="Study_Hours",
 y="Exam_Score",
 color="red"
 )
plt.xlabel("Study Hours")
plt.ylabel("Exam Score")
plt.title("Study Hours vs Exam Score")

plt.show()

sns.scatterplot(
    data=data,
    x="Attendance",
    y="Exam_Score",
    color="green"
)

plt.xlabel("Attendance")
plt.ylabel("Exam Score")
plt.title("Attendance vs Exam Score")

plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


df = pd.read_csv("/content/student_performance_dirty (1).csv")


df['Final_Score'] = (
    df['Assignments_Score'] +
    df['Exam_Score'] +
    df['Projects_Score']
)


df.dropna(inplace=True)

np.random.seed(42)

df['Exam_Score_Noise'] = (
    df['Exam_Score'] +
    np.random.normal(0, 5, len(df))
)

X = df[[
    'Study_Hours',
    'Attendance',
    'Assignments_Score',
    'Projects_Score',
    'Exam_Score_Noise'
]]

y = df['Final_Score']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = LinearRegression()


model.fit(X_train, y_train)

print("Model Trained Successfully!")

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n===== Evaluation Metrics =====")

print("MAE =", mae)
print("MSE =", mse)
print("R2 Score =", r2)

plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Scores")
plt.ylabel("Predicted Scores")

plt.title("Actual vs Predicted Scores")

plt.show()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

df = pd.read_csv("cleaned_dataset.csv")

X = df[['Study_Hours', 'Attendance', 'Exam_Score']]


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertias = []
for k in range(2, 9):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

plt.plot(range(2, 9), inertias, 'o-')
plt.xlabel("k")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

df.loc[X.index, 'Cluster'] = clusters

order = df.groupby('Cluster')['Exam_Score'].mean().sort_values()
label_map = {
    order.index[0]: 'Weak',
    order.index[1]: 'Average',
    order.index[2]: 'Excellent'
}
df['Level'] = df['Cluster'].map(label_map)

print(df['Level'].value_counts())

colors = {'Weak': 'red', 'Average': 'orange', 'Excellent': 'green'}
for level, grp in df.groupby('Level'):
    plt.scatter(grp['Study_Hours'], grp['Exam_Score'],
                c=colors[level], label=level)

plt.xlabel("Study Hours")
plt.ylabel("Exam Score")
plt.title("K-Means Clustering")
plt.legend()
plt.show()